services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - "3001:3000"
      - "5555:5555"
    volumes:
      - .:/app:cached
      - ./node_modules:/app/node_modules
    networks:
      - app_network
    depends_on:
      - db
    env_file: .env

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports: 
      - "$DATABASE_PORT:5432"
    networks:
      - app_network
    env_file: .env

volumes:
  node_modules:
  postgres_data:

networks:
  app_network:
    driver: bridge