name: Build & Prisma Generate Verification

on:
  push:
    branches: [ main, copilot/**, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres" --health-interval=5s --health-timeout=5s --health-retries=10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Prisma generate (with import fix)
        run: npm run prisma:generate

      - name: Prisma migrate & seed
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres?schema=public
        run: |
          npx prisma migrate deploy
          npm run seed:minimal

      - name: Type check & build
        run: npm run build

      - name: Smoke GraphQL (required)
        env:
          SMOKE_GRAPHQL_ENDPOINT: http://localhost:3000/api/graphql
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres?schema=public
        run: |
          # Start server in background (needs DB for auth/login paths)
          npm run dev &
          SERVER_PID=$!
          npx wait-on http://localhost:3000
          npm run test:smoke:graphql
          kill $SERVER_PID || true
